<!DOCTYPE html>
<html>
<head>
	<title>Sala</title>
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/chat.css?v=<?php echo time(); ?>">
</head>
<body>
    <?php echo'<h2>Sala '.$_GET['room'].'</h2>'; 
    echo'<a href="index.php">Volver a la página principal</a>';?>
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="container">
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>

                <ul class="list-unstyled chat-list mt-2 mb-0">
                    <?php
                        if($allUsers){
                            foreach($allUsers as $usuario){
                                if( $usuario->getStatus() == 0){
                                echo '<li class="clearfix">
                                                <img src="views/img/'.$usuario->getImg().'" alt="avatar">
                                                <div class="about">
                                                <div class="name"> '.$usuario->getName().' </div>
                                                <div class="status"> <i class="fa fa-circle offline"></i> '.$usuario->getStatus().' </div>                                            
                                            </div>
                                        </li>';
                                }else{
                                    echo '<li class="clearfix">
                                                <img src="views/img/'.$usuario->getImg().'" alt="avatar">
                                                <div class="about">
                                                    <div class="name"> '.$usuario->getName().'</div>
                                                    <div class="status"> <i class="fa fa-circle online"></i> '.$usuario->getStatus().' </div>
                                                </div>
                                            </li> ';
                                }

                            }
                        }
                    ?>
                    
                            



                </ul>


            </div>

            <div class="chat">
                <div class="chat-history">
                    <ul class="m-b-0">

                        <?php
                            if($roomMessages){
                                foreach($roomMessages as $message){
                                    if( $message->iduser == $_SESSION['user']->getID()){
                                        echo ' 
                                        <li class="clearfix">
                                        <div style="display:flex;flex-direction:column" class="float-right"> 
                                            <div class="message-data text-right "  >
                                            <span class="message-data-time"> '.UserRepository::getOneUsuario($message->iduser)->getName().'</span>
                                            <img src="views/img/'.$_SESSION['user']->getImg().'" alt="avatar">
                                            </div>
                                            <div class="message other-message float-right"> '.$message->content.'</div>
                                        </div>

                                        </li>';
                                    }else{
                                        echo ' <li class="clearfix">
                                        <div class="message-data text-left">
                                        <span class="message-data-time"> '.UserRepository::getOneUsuario($message->iduser)->getName().'</span>
                                        <img src="views/img/'.UserRepository::getOneUsuario(($message->iduser))->getImg().'" alt="avatar">
                                        </div>
                                        <div class="message other-message float-left"> '.$message->content.' </div>
                                        </li>';
                                    }
                                }
                            }

                        ?>
                    </ul>
                </div>

                <div class="chat-message clearfix">
                    <div class="input-group mb-0">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-send"></i></span>
                        </div>
                       <?php echo'<form method="POST" action="index.php?room='.$_GET['room'].'"> 
                            <input type="text" class="form-control" name="send" placeholder="Enter text here...">   
                        </form>';
                        ?>
                    </div>
                </div>


</body>
</html>